=== alvarogutierrez-web/ASIX-LMSGI04.1-AlvaroGutierrez/Tasca LMSGI04.1/catalogo.dtd
<!ELEMENT catalogo (single | album)+>

<!--información-->
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT grupo (#PCDATA)>

<!ELEMENT miembros (miembro+)>
<!ELEMENT miembro (nombre)>
<!ELEMENT nombre (#PCDATA)>

<!--single-->      <!--sin símbolo:solo 1 vez / ?: 0 o 1 vez (opcional) / *: 0 o más veces / +: 1 o más veces-->
<!ELEMENT single (titulo, descripcion?, pais, idioma, genero*, grupo, miembros, duracion)>
<!ELEMENT duracion (#PCDATA)>

<!ATTLIST single
    codigo CDATA #REQUIRED
>

<!--album-->
<!ELEMENT album (titulo, descripcion?, pais, idioma, genero*, grupo, miembros, numero_canciones, canciones)>
<!ELEMENT numero_canciones (#PCDATA)>

<!ELEMENT canciones (cancion+)>
<!ELEMENT cancion (titulo_cancion, duracion_cancion)>
<!ELEMENT titulo_cancion (#PCDATA)>
<!ELEMENT duracion_cancion (#PCDATA)>

<!ATTLIST album
    codigo CDATA #REQUIRED
>

<!ATTLIST cancion
    numero CDATA #REQUIRED
>

<!--atributo sexo-->
<!ATTLIST miembro
    sexo (masculino | femenino) #REQUIRED
>

=== alvarogutierrez-web/ASIX-LMSGI04.1-AlvaroGutierrez/Tasca LMSGI04.1/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "catalogo.dtd">

<catalogo>

    <single codigo="S001">
        <titulo>Imagine</titulo>
        <descripcion>Canción icónica por la paz</descripcion>
        <pais>Reino Unido</pais>
        <idioma>Inglés</idioma>
        <genero>Rock and Roll</genero>
        <grupo>John Lennon</grupo>
        <miembros>
            <miembro sexo="masculino">
                <nombre>John Lennon</nombre>
            </miembro>
        </miembros>
        <duracion>3.1</duracion>
    </single>

    <album codigo="A001">
        <titulo>Thriller</titulo>
        <descripcion>Álbum más vendido de la historia</descripcion>
        <pais>Estados Unidos</pais>
        <idioma>Inglés</idioma>
        <genero>Pop</genero>
        <genero>Soul</genero>
        <grupo>Michael Jackson</grupo>

        <miembros>
            <miembro sexo="masculino">
                <nombre>Michael Jackson</nombre>
            </miembro>
        </miembros>

        <numero_canciones>2</numero_canciones>

        <canciones>
            <cancion numero="1">
                <titulo_cancion>Thriller</titulo_cancion>
                <duracion_cancion>5.57</duracion_cancion>
            </cancion>
            <cancion numero="2">
                <titulo_cancion>Beat It</titulo_cancion>
                <duracion_cancion>4.18</duracion_cancion>
            </cancion>
        </canciones>
    </album>

</catalogo>
